#!/bin/bash -x

curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh > ~/.git-prompt.sh

ln -sf ~/.dotfiles/zshrc ~/.zshrc
ln -sf ~/.dotfiles/bashrc ~/.bashrc
ln -sf ~/.dotfiles/aliases ~/.aliases
ln -sf ~/.dotfiles/aliases_zsh ~/.aliases_zsh
ln -sf ~/.dotfiles/functions ~/.functions
ln -sf ~/.dotfiles/vimrc ~/.vimrc
ln -sf ~/.dotfiles/gitconfig ~/.gitconfig

mkdir -p ~/.local/share/newsbeuter
ln -sf ~/.dotfiles/urls ~/.local/share/newsbeuter/urls
ln -sf ~/.dotfiles/config ~/.local/share/newsbeuter/config
mkdir -p ~/.newsbeuter
ln -sf ~/.dotfiles/urls ~/.newsbeuter/urls
ln -sf ~/.dotfiles/config ~/.newsbeuter/config

ln -sf ~/.dotfiles/sqliterc ~/.sqliterc

ln -sf ~/.dotfiles/vs-code-settings.json ~/.config/Code/User/settings.json
mkdir -p ~/.config/VSCodium/User/
ln -sf ~/.dotfiles/vs-code-settings.json ~/.config/VSCodium/User/settings.json

