#!/bin/bash -x

ln -sf ~/.dotfiles/zshrc ~/.zshrc
ln -sf ~/.dotfiles/aliases ~/.aliases
ln -sf ~/.dotfiles/aliases_zsh ~/.aliases_zsh
ln -sf ~/.dotfiles/functions ~/.functions
ln -sf ~/.dotfiles/vimrc ~/.vimrc
ln -sf ~/.dotfiles/gitconfig ~/.gitconfig

