#!/bin/bash -x

ln -sf ~/.dotfiles/zshrc ~/.zshrc
ln -sf ~/.dotfiles/aliases ~/.aliases
ln -sf ~/.dotfiles/aliases_zsh ~/.aliases_zsh
ln -sf ~/.dotfiles/functions ~/.functions
ln -sf ~/.dotfiles/vimrc ~/.vimrc
ln -sf ~/.dotfiles/gitconfig ~/.gitconfig

mkdir -p ~/.local/share/newsbeuter
ln -sf ~/.dotfiles/urls ~/.local/share/newsbeuter/urls
ln -sf ~/.dotfiles/config ~/.local/share/newsbeuter/config

